### PR TITLE
Add absolute path posix option

### PR DESCRIPTION
**Pull request by phuein**
What do you think about adding an optional absolute path posix copy option? I find myself needing it often, and it seems easy enough to add.

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
Did you edit the JS file by accident? I see weird things in `extension.ts`

**Comment by phuein** [comment]
I added an absolute path in posix option to the addon, by editing my existing version of it as installed from the VS Code marketplace normally. What do you see that's weird?

**Comment by bpasero** [comment]
The contents of the `extension.ts` look like they are from the compiled version `extension.js`

**Comment by phuein** [comment]
Odd that the file is still named `.ts` then. I'll fork your repo and make the changes properly then, if you think you'd accept this addition in principal.

**Pull request closed without merging**
